var brick_wall = {'name':'brick_wall', 'constructor':'brick_wall', 'angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[1,1,1,1]}
var brick_wall_top = {'name':'brick_wall', 'constructor':'brick_wall_top','angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[1,1,0,0]}
var brick_wall_right = {'name':'brick_wall', 'constructor':'brick_wall_right','angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[0,1,0,1]}
var brick_wall_bottom = {'name':'brick_wall', 'constructor':'brick_wall_bottom','angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[0,0,1,1]}
var brick_wall_left = {'name':'brick_wall', 'constructor':'brick_wall_left','angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[1,0,1,0]}
var brick_wall_left_angle = {'name':'brick_wall','angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[0,0,1,0]}
var brick_wall_right_angle = {'name':'brick_wall','angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[0,0,0,1]}

var concrete_wall = {'name':'concrete_wall', 'constructor':'concrete_wall', 'angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[1,1,1,1]}
var concrete_wall_top = {'name':'concrete_wall', 'constructor':'concrete_wall_top','angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[1,1,0,0]}
var concrete_wall_right = {'name':'concrete_wall', 'constructor':'concrete_wall_right','angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[0,1,0,1]}
var concrete_wall_bottom = {'name':'concrete_wall', 'constructor':'concrete_wall_bottom','angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[0,0,1,1]}
var concrete_wall_left = {'name':'concrete_wall', 'constructor':'concrete_wall_left','angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[1,0,1,0]}
var concrete_wall_left_angle = {'name':'concrete_wall','angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[0,0,1,0]}
var concrete_wall_right_angle = {'name':'concrete_wall','angle':0,'type':'obstacle','speed':0,'life':1, 'permit':'.png', 'placing':[0,0,0,1]}

var forest_wall = {'name':'forest_wall', 'constructor':'forest_wall','angle':0,'type':'forest','speed':0,'life':0, 'permit':'.png', 'placing':[1,1,1,1]}
var forest_wall_top = {'name':'forest_wall', 'constructor':'forest_wall_top','angle':0,'type':'forest','speed':0,'life':0, 'permit':'.png', 'placing':[1,1,0,0]}
var forest_wall_right = {'name':'forest_wall', 'constructor':'forest_wall_right','angle':0,'type':'forest','speed':0,'life':0, 'permit':'.png', 'placing':[0,1,0,1]}
var forest_wall_bottom = {'name':'forest_wall', 'constructor':'forest_wall_bottom','angle':0,'type':'forest','speed':0,'life':0, 'permit':'.png', 'placing':[0,0,1,1]}
var forest_wall_left = {'name':'forest_wall', 'constructor':'forest_wall_left','angle':0,'type':'forest','speed':0,'life':0, 'permit':'.png', 'placing':[1,0,1,0]}

var river_wall = {'name':'river_wall', 'constructor':'river_wall','angle':0,'type':'river','speed':0,'life':0, 'permit':'.gif', 'placing':[1,1,1,1]}
var river_wall_top = {'name':'river_wall', 'constructor':'river_wall_top','angle':0,'type':'river','speed':0,'life':0, 'permit':'.gif', 'placing':[1,1,0,0]}
var river_wall_right = {'name':'river_wall', 'constructor':'river_wall_right','angle':0,'type':'river','speed':0,'life':0, 'permit':'.gif', 'placing':[0,1,0,1]}
var river_wall_bottom = {'name':'river_wall', 'constructor':'river_wall_bottom','angle':0,'type':'river','speed':0,'life':0, 'permit':'.gif', 'placing':[0,0,1,1]}
var river_wall_left = {'name':'river_wall', 'constructor':'river_wall_left','angle':0,'type':'river','speed':0,'life':0, 'permit':'.gif', 'placing':[1,0,1,0]}
var road = '';
field1 = {
        'stage':1,
        'battlefield':[[road, road, road, road, road, road, road, road, road, road, road, road, road], [forest_wall, road, road, road, road, road, forest_wall, road, road, road, road, road, forest_wall], [forest_wall, road, road, road, road, road, forest_wall, road, road, road, road, road, forest_wall], [road, road, road, road, road, road, road, road, road, road, road, road, road], [brick_wall, road, road, road, road, forest_wall, forest_wall, forest_wall, road, road, road, road, brick_wall], [brick_wall, river_wall, river_wall, river_wall, river_wall, brick_wall, brick_wall, brick_wall, river_wall, river_wall, river_wall, river_wall, brick_wall], [concrete_wall, forest_wall, road, road, road, forest_wall, brick_wall, forest_wall, road, road, road, forest_wall, concrete_wall], [forest_wall, forest_wall, road, road, road, road, concrete_wall, road, road, road, road, forest_wall, forest_wall], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, forest_wall, forest_wall_top, forest_wall_top, road, forest_wall_top, forest_wall_top, forest_wall, road, road, road], [road, road, road, forest_wall, river_wall_left, river_wall_left, river_wall_left, road, road, forest_wall, road, road, road]]
        }
        
var field2 = {
        'stage':2,
        'battlefield':[[road, road, road, road, road, road, road, road, road, road, road, road, road], [forest_wall, forest_wall, forest_wall, river_wall, river_wall, river_wall, river_wall, river_wall, river_wall, river_wall, forest_wall, forest_wall, forest_wall], [forest_wall, road, road, road, road, road, road, road, road, road, road, road, forest_wall], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, brick_wall_bottom, brick_wall, brick_wall_bottom, road, road, road, road, road], [road, road, road, road, brick_wall_right, brick_wall_left, brick_wall, brick_wall_right, brick_wall_left, road, road, road, road], [road, road, road, road, road, brick_wall, brick_wall_bottom, brick_wall, road, road, road, road, road], [road, road, road, road, road, brick_wall_right, brick_wall_bottom, brick_wall_left, road, road, road, road, road], [road, road, road, forest_wall_right, brick_wall_bottom, road, brick_wall_right, road, brick_wall_bottom, forest_wall_left, road, road, road], [river_wall_top, river_wall_top, river_wall_top, road, brick_wall_top, brick_wall_top, brick_wall, brick_wall_top, brick_wall_top, road, river_wall_top, river_wall_top, river_wall_top], [forest_wall, forest_wall, concrete_wall, concrete_wall, concrete_wall, road, brick_wall, road, concrete_wall, concrete_wall, concrete_wall, forest_wall, forest_wall], [road, road, road, road, road, road, brick_wall, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road]]
        }
        
var field3 = {
        'stage':3,
        'battlefield':[[road, road, road, road, road, road, road, road, road, road, road, road, road], [concrete_wall, concrete_wall, river_wall, concrete_wall, concrete_wall, concrete_wall, river_wall, concrete_wall, concrete_wall, concrete_wall, river_wall, concrete_wall, concrete_wall], [road, road, road, road, road, road, concrete_wall_bottom, road, road, road, road, road, road], [road, road, road, road, road, concrete_wall_bottom, forest_wall, concrete_wall_bottom, road, road, road, road, road], [road, road, road, road, concrete_wall_bottom, forest_wall, forest_wall, forest_wall, concrete_wall_bottom, road, road, road, road], [road, road, road, concrete_wall_bottom, forest_wall, forest_wall, forest_wall, forest_wall, forest_wall, concrete_wall_bottom, road, road, road], [road, road, brick_wall_bottom, forest_wall, forest_wall, forest_wall, forest_wall, forest_wall, forest_wall, forest_wall, brick_wall_bottom, road, road], [road, road, road, brick_wall_top, brick_wall_top, brick_wall_top, brick_wall, brick_wall_top, brick_wall_top, brick_wall_top, road, road, road], [road, road, concrete_wall_top, concrete_wall_top, concrete_wall_top, river_wall_top, brick_wall_top, river_wall_top, concrete_wall_top, concrete_wall_top, concrete_wall_top, road, road], [river_wall_left, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road]]
        }
        
var field4 = {
        'stage':'4',
        'battlefield':[[road, road, road, road, road, road, road, road, road, road, road, road, road], [brick_wall, road, road, brick_wall, road, road, brick_wall, road, road, brick_wall, road, road, brick_wall], [brick_wall, road, road, brick_wall, road, road, brick_wall, road, road, brick_wall, road, road, brick_wall], [brick_wall, road, road, brick_wall, road, brick_wall, brick_wall, brick_wall, road, brick_wall, road, road, brick_wall], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, brick_wall, brick_wall, road, brick_wall, forest_wall, forest_wall, forest_wall, brick_wall, road, brick_wall, brick_wall, road], [road, brick_wall, road, road, brick_wall, road, road, road, brick_wall, road, road, brick_wall, road], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, forest_wall, forest_wall, road, road, road, forest_wall, forest_wall, road, road, road], [road, road, road, forest_wall, road, road, road, road, road, forest_wall, road, road, road]]
        }
        
var field5 = {
        'stage':'5',
        'battlefield':[[road, road, road, road, road, road, road, road, road, road, road, road, road], [brick_wall, road, road, road, road, road, road, road, road, road, road, road, road], [road, river_wall_left, road, brick_wall, brick_wall, brick_wall, road, road, brick_wall, brick_wall, brick_wall, brick_wall, road], [road, road, brick_wall, river_wall, brick_wall, river_wall, brick_wall, brick_wall, brick_wall, river_wall, brick_wall, river_wall, brick_wall], [road, road, brick_wall, brick_wall, forest_wall, brick_wall, brick_wall, brick_wall, brick_wall, brick_wall, forest_wall, brick_wall, brick_wall], [road, road, brick_wall, road, road, road, brick_wall, brick_wall, brick_wall, road, road, road, brick_wall], [road, brick_wall, road, brick_wall, brick_wall, brick_wall, road, road, brick_wall, brick_wall, brick_wall, brick_wall, road], [brick_wall, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road], [road, road, road, road, road, road, road, road, road, road, road, road, road]]
        }
